language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=26.0.2
    - ADB_INSTALL_TIMEOUT=5
    - EMULATOR_API_LEVEL=27
    - SYSTEM_IMAGE=/usr/local/android-sdk/system-images/android-27/default/x86/kernel-ranchu-64
    - ANDROID_SDK_ROOT=/usr/local/android-sdk

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-$EMULATOR_API_LEVEL

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - chmod +x gradlew
  - chmod +x scripts/build_publish.sh
  - chmod +x scripts/build_compile.sh
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools" "build-tools;26.0.2" "extras;android;m2repository"
  - export PATH=${ANDROID_SDK_ROOT}/tools/bin:$PATH
  - ./gradlew dependencies || true

before_script:
  - git lfs pull
  - find /usr/local/android-sdk/system-images -type f
  - echo no | android create avd --force -n test --tag android-$EMULATOR_API_LEVEL --abi x86 -c 100M
  - emulator -avd test -kernel $SYSTEM_IMAGE -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./scripts/build_publish.sh
#  - "./gradlew clean build -PdisablePreDex --stacktrace"

#after_success:
#  - ./scripts/build_publish.sh