language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=26.0.2
    - ADB_INSTALL_TIMEOUT=5
    - EMULATOR_API_LEVEL=29
    - ABI=x86_64
    - EMU_FLAVOR=default
    - EMU_CHANNEL=""
    - ANDROID_HOME=${HOME}/android-sdk
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - chmod +x gradlew
  - chmod +x scripts/build_publish.sh
  - chmod +x scripts/build_compile.sh
  - ./gradlew dependencies || true

before_script:
  - git lfs pull
  # Download required emulator tools
  - echo y | sdkmanager --no_https "platforms;android-$EMULATOR_API_LEVEL" >/dev/null # We need the API of the emulator we will run
  - echo y | sdkmanager --no_https $EMU_CHANNEL "emulator" >/dev/null
  - echo y | sdkmanager --no_https "system-images;android-$EMULATOR_API_LEVEL;$EMU_FLAVOR;$ABI" >/dev/null # install our emulator
  #- echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a -c 100M
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API_LEVEL;$EMU_FLAVOR;$ABI" -c 10M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./scripts/build_publish.sh
#  - "./gradlew clean build -PdisablePreDex --stacktrace"

#after_success:
#  - ./scripts/build_publish.sh