language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=29.0.2
    - ADB_INSTALL_TIMEOUT=5

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - chmod +x gradlew
  - chmod +x scripts/build_publish.sh
  - chmod +x scripts/build_compile.sh
  - ./gradlew dependencies || true

before_script:
  - git lfs pull

script:
  - ./scripts/build_compile.sh
#  - "./gradlew clean build -PdisablePreDex --stacktrace"

after_success:
  - ./scripts/build_publish.sh